name: Deploy to Timeweb

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '24'
          cache: 'npm'

      - name: Install Frontend Dependencies
        run: cd frontend && npm ci

      - name: Build Frontend
        run: cd frontend && npm run build

      - name: Install Backend Dependencies
        run: cd backend && npm ci

      - name: Build Backend
        run: cd backend && npm run build

      - name: Deploy to Timeweb
        env:
          SSH_KEY: ${{ secrets.SSH_KEY }}
          SSH_HOST: ${{ secrets.SSH_HOST }}
          SSH_USER: ${{ secrets.SSH_USER }}
        run: |
          echo "$SSH_KEY" > key.pem
          chmod 600 key.pem
          ssh -o StrictHostKeyChecking=no -i key.pem $SSH_USER@$SSH_HOST << 'EOF'
            mkdir -p ~/public_html ~/node_app
            exit
          EOF
          scp -i key.pem -r frontend/dist/* $SSH_USER@$SSH_HOST:~/public_html/
          scp -i key.pem -r backend/dist/* backend/prisma backend/package.json backend/.env $SSH_USER@$SSH_HOST:~/node_app/
          ssh -i key.pem $SSH_USER@$SSH_HOST << 'EOF'
            cd ~/node_app
            npm ci --production
            npx prisma generate
            pm2 restart vmetke-backend || pm2 start dist/app.js --name vmetke-backend
            exit
          EOF